### PR TITLE
cmbreps now also works for more than 2 replicates (idr + mean + max)

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
As the title says; now **cmbreps also works for more than 2 replicates**!! It does however depend on **scipy** for the calculation of fisher's method (which would be an extra dependency).
```
test1 
chr1    0   100  0.9
chr1    100 200  0.3
chr1    200 300  0.4
chr2    0   100  0.9
chr2    100 200  0.3
chr2    200 300  0.4
```

```
test2
chr1    0   150 0.9
chr1    150 250 0.2
chr1    250 300 0.4
chr2    0   150 0.9
chr2    150 250 0.2
chr2    250 300 0.4
```

```
test3
chr1    0   100 0.3
chr1    100 150 0.6
chr1    150 175 0.5
chr1    175 200 0.3
chr1    200 300 0.2
chr1    0   100 0.3
chr1    100 150 0.6
chr1    150 200 0.3
chr1    200 300 0.4
chr3    0   100 0.2
```

```
macs2 cmbreps -i test1 test2 test3 -o /dev/stdout -m max
INFO  @ Mon, 19 Aug 2019 16:34:43: Read and build bedGraph for each replicate... 
INFO  @ Mon, 19 Aug 2019 16:34:43: Read file #1 
INFO  @ Mon, 19 Aug 2019 16:34:43: Read file #2 
INFO  @ Mon, 19 Aug 2019 16:34:43: Read file #3 
INFO  @ Mon, 19 Aug 2019 16:34:43: combining tracks 1-3 with method 'max' 
INFO  @ Mon, 19 Aug 2019 16:34:43: Write bedGraph of combined scores... 
track type=bedGraph name="MAX_combined_scores" description="Scores calculated by MAX" visibility=2 alwaysZero=on
chr1	0	150	0.90000
chr1	150	175	0.50000
chr1	175	200	0.30000
chr1	200	300	0.40000
INFO  @ Mon, 19 Aug 2019 16:34:43: Finished 'max'! Please check '/dev/stdout'!
```

### CODE REVIEW

**Comment by taoliu** [comment]
@Maarten-vd-Sande Thank you for the codes! The reason why I only implemented the function to combine 2 replicates is that it's so simple to compute when using Fisher's method. If more replicates should be considered, I agree that we'd better just use scipy function to compute.

**Comment by Maarten-vd-Sande** [comment]
Great, so there is no objection against scipy as dependency? Good catch about the log10 pvalues! I'll make the change tomorrow.

**Comment by taoliu** [comment]
No objection, although I still prefer less independency to other packages. I will keep scipy for this PR until I implement the chi-square survival function by myself in either C or Cython.

**Comment by Maarten-vd-Sande** [comment]
@taoliu I don't know how to flag for a new review so I am doing it like this.

**Comment by taoliu** [comment]
Thank you @Maarten-vd-Sande , your contribution has been merged to MACS2 master branch :)

**Comment by Maarten-vd-Sande** [comment]
Thank you too for your fast responses

**Comment by Maarten-vd-Sande** [comment]
Btw any estimated release date for 2.1.3?

**Comment by taoliu** [comment]
@Maarten-vd-Sande I plan to review and merge another PR --WACS before 2.1.3.

**Comment by taoliu** [comment]
@Maarten-vd-Sande FYI, I have implemented a simple Chisq pvalue function to replace scipy.stats.combine_pvalues function in PR #307

**Comment by Maarten-vd-Sande** [comment]
@taoliu cool looks good, and removes a big dependency!

**Pull request merged**
